name: CI/CD for Airflow Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Build Docker image
      run: |
        docker build -t my-airflow-image .

    - name: Run Docker Compose (Test Containers)
      run: |
        docker-compose -f docker-compose.yaml up -d
        docker-compose ps

    - name: Wait for Airflow to be ready
      run: |
        echo "Waiting for Airflow Webserver to be ready..."
        while ! docker-compose logs airflow-webserver | grep -q "Listening at: http://0.0.0.0:8080"; do
          echo "Waiting for Airflow..."
          sleep 10
        done
        echo "Airflow is ready!"

    - name: Wait for Scheduler to load DAGs
      run: sleep 60

    - name: List DAGs to verify availability
      run: |
        docker-compose exec -T airflow-webserver airflow dags list

    - name: Unpause DAG (if necessary)
      run: |
        docker-compose exec -T airflow-webserver airflow dags unpause data_pipeline

    - name: Run Airflow DAG tests
      run: |
        docker-compose exec -T airflow-webserver airflow dags trigger -e $(date +%Y-%m-%d) data_pipeline

    - name: Shut down Docker containers
      run: |
        docker-compose down

    - name: Clean up Docker images
      run: |
        docker rmi my-airflow-image
